/-
SPDX-License-Identifier: Apache-2.0
Authors: Formal Frontier Agents
-/

module

import all ProjectiveSpace.SymmetricAlgebraClosedPoint
import all ProjectiveSpace.SymmetricAlgebraAffineClosedPoint

#print axioms ProjectiveSpace.instDecidableEqSymmetricAlgebraClosedPoint
#print axioms ProjectiveSpace.instDecidableEqSymmetricAlgebraAffineClosedPoint
#print axioms ProjectiveSpace.dualConeLineMap
#print axioms ProjectiveSpace.symmetricAlgebraHomogeneousCoordinateMap
#print axioms ProjectiveSpace.symmetricAlgebraHomogeneousCoordinateMap_ι
#print axioms ProjectiveSpace.homogeneousCoordinateMap_comp_equivMvPolynomial
#print axioms ProjectiveSpace.symmetricAlgebraHomogeneousCoordinateIdeal
#print axioms ProjectiveSpace.symmetricAlgebraHomogeneousCoordinatePointOfBasis
#print axioms ProjectiveSpace.symmetricAlgebraHomogeneousCoordinatePointOfBasis_toIdeal
#print axioms ProjectiveSpace.symmetricAlgebraHomogeneousCoordinatePointOfBasis_eq
#print axioms ProjectiveSpace.symmetricAlgebraHomogeneousCoordinatePoint
#print axioms ProjectiveSpace.symmetricAlgebraHomogeneousCoordinatePoint_toIdeal
#print axioms ProjectiveSpace.symmetricAlgebraHomogeneousCoordinatePoint_eq_ofBasis
#print axioms ProjectiveSpace.symmetricAlgebraHomogeneousCoordinatePoint_map
#print axioms ProjectiveSpace.projectivizationEquivCoordinates
#print axioms ProjectiveSpace.projectivizationEquivCoordinates_mk
#print axioms ProjectiveSpace.projectivizationEquivSymmetricAlgebraClosedPointsOfBasis
#print axioms ProjectiveSpace.projectivizationEquivSymmetricAlgebraClosedPointsOfBasis_mk
#print axioms ProjectiveSpace.projectivizationEquivSymmetricAlgebraClosedPointsOfBasis_eq
#print axioms ProjectiveSpace.projectivizationEquivSymmetricAlgebraClosedPoints
#print axioms ProjectiveSpace.projectivizationEquivSymmetricAlgebraClosedPoints_mk
#print axioms ProjectiveSpace.projectivizationEquivSymmetricAlgebraClosedPointsOfBasis_eq_canonical
#print axioms ProjectiveSpace.projectivizationEquivSymmetricAlgebraClosedPoints_naturality
#print axioms ProjectiveSpace.oneDimensionalSubspacesEquivSymmetricAlgebraClosedPoints
#print axioms ProjectiveSpace.symmetricAlgebraAffineCoordinateMap
#print axioms ProjectiveSpace.symmetricAlgebraAffineCoordinateMap_ι
#print axioms ProjectiveSpace.symmetricAlgebraAffineCoordinateIdeal
#print axioms ProjectiveSpace.symmetricAlgebraAffineCoordinateIdeal_isMaximal
#print axioms ProjectiveSpace.symmetricAlgebraAffineCoordinatePoint
#print axioms ProjectiveSpace.symmetricAlgebraAffineCoordinatePoint_asIdeal
#print axioms ProjectiveSpace.symmetricAlgebraAffineCoordinatePoint_isClosed
#print axioms ProjectiveSpace.symmetricAlgebraAffineClosedPoint
#print axioms ProjectiveSpace.mvPolynomialAffineCoordinatePoint
#print axioms ProjectiveSpace.mvPolynomialAffineCoordinatePoint_asIdeal
#print axioms ProjectiveSpace.mvPolynomialAffineCoordinatePoint_isClosed
#print axioms ProjectiveSpace.mvPolynomialAffineClosedPoint
#print axioms ProjectiveSpace.mvPolynomialAffineClosedPoint_injective
#print axioms ProjectiveSpace.mvPolynomialAffineClosedPoint_surjective
#print axioms ProjectiveSpace.mvPolynomialAffineClosedPointsEquiv
#print axioms ProjectiveSpace.mvPolynomialAffineClosedPointsEquiv_apply
#print axioms ProjectiveSpace.primeSpectrumClosedPointsEquivOfRingEquiv
#print axioms ProjectiveSpace.primeSpectrumClosedPointsEquivOfRingEquiv_apply_coe
#print axioms ProjectiveSpace.affineCoordinateMap_comp_equivMvPolynomial
#print axioms ProjectiveSpace.mvPolynomialAffineCoordinatePoint_comap_equivMvPolynomial
#print axioms ProjectiveSpace.symmetricAlgebraAffineClosedPointOfBasis
#print axioms ProjectiveSpace.symmetricAlgebraAffineClosedPointOfBasis_eq
#print axioms ProjectiveSpace.symmetricAlgebraAffineClosedPoint_injective
#print axioms ProjectiveSpace.symmetricAlgebraAffineClosedPoint_surjective_of_basis
#print axioms ProjectiveSpace.symmetricAlgebraAffineClosedPoint_surjective
#print axioms ProjectiveSpace.symmetricAlgebraAffineClosedPointsEquiv
#print axioms ProjectiveSpace.symmetricAlgebraAffineClosedPointsEquiv_apply
#print axioms ProjectiveSpace.symmetricAlgebraAffineClosedPointsEquiv_apply_eq_comap_ofBasis
#print axioms ProjectiveSpace.symmetricAlgebraAffineClosedPointsEquiv_apply_eq_ofBasis
#print axioms ProjectiveSpace.symmetricAlgebraAffineClosedPointsEquivOfLinearEquiv
#print axioms ProjectiveSpace.symmetricAlgebraAffineClosedPointsEquivOfLinearEquiv_apply_coe
#print axioms ProjectiveSpace.symmetricAlgebraAffineCoordinatePoint_map
#print axioms ProjectiveSpace.symmetricAlgebraAffineClosedPoint_naturality
#print axioms ProjectiveSpace.symmetricAlgebraAffineClosedPointsEquiv_naturality
#print axioms ProjectiveSpace.polynomialEval_comp_symmetricAlgebraHomogeneousCoordinateMap
