/-
SPDX-License-Identifier: Apache-2.0
Copyright (c) 2024 Andrew Yang. All rights reserved.
Copyright (c) 2022 Jujian Zhang. All rights reserved.
Authors: Formal Frontier Agents
  Andrew Yang (native Proj chart and gluing construction in mathlib)
  Jujian Zhang and Eric Wieser (homogeneous-localization construction in mathlib)
Adapted material released under Apache 2.0, as in mathlib's LICENSE.
-/
module

public import GradedRings.HomogeneousLocalizationMap
public import Mathlib.AlgebraicGeometry.ProjectiveSpectrum.Basic
public import Mathlib.AlgebraicGeometry.Pullbacks

@[expose] public section

set_option warningAsError true

/-!
# Positive-degree-scaled Proj maps on their natural open domain

An ordinary ring homomorphism taking the degree `n` piece into degree `d * n`
for a positive `d` gives a morphism from the union of its image basic opens
to the source Proj. The underlying rings and their gradings share the universe
required by the native scheme category, while the grading-value types may differ.
-/

noncomputable section

namespace AlgebraicGeometry.Proj

open CategoryTheory HomogeneousLocalization TopologicalSpace

universe u v w

variable {A B : Type u} {σ : Type v} {τ : Type w}
variable [CommRing A] [SetLike σ A] [AddSubgroupClass σ A]
  (𝒜 : ℕ → σ) [GradedRing 𝒜]
variable [CommRing B] [SetLike τ B] [AddSubgroupClass τ B]
  (ℬ : ℕ → τ) [GradedRing ℬ]

/-- The ideal generated by the images of all positive homogeneous forms. -/
def imageIrrelevant (f : A →+* B) : Ideal B :=
  Ideal.map f (HomogeneousIdeal.irrelevant 𝒜).toIdeal

/-- An image distinguished open, indexed by a positive homogeneous source element. -/
def chartOpen (f : A →+* B) (i : Σ n : PNat, 𝒜 n) : (Proj ℬ).Opens :=
  basicOpen ℬ (f (i.2 : A))

/-- The natural domain of a positive-degree-scaled Proj map. -/
def degreeScaledDomain (f : A →+* B) : (Proj ℬ).Opens :=
  ⨆ i : Σ n : PNat, 𝒜 n, chartOpen 𝒜 ℬ f i

theorem degreeScaledDomain_eq_zeroLocus_compl (f : A →+* B) :
    (degreeScaledDomain 𝒜 ℬ f : Set (Proj ℬ)) =
      (ProjectiveSpectrum.zeroLocus ℬ (imageIrrelevant 𝒜 f) : Set (Proj ℬ))ᶜ := by
  classical
  ext x
  simp only [degreeScaledDomain, chartOpen, TopologicalSpace.Opens.coe_iSup, Set.mem_iUnion]
  change (∃ i : Σ n : PNat, 𝒜 n, f (i.2 : A) ∉ x.asHomogeneousIdeal) ↔
    ¬imageIrrelevant 𝒜 f ≤ x.asHomogeneousIdeal.toIdeal
  constructor
  · rintro ⟨⟨⟨n, hn⟩, ⟨a, ha⟩⟩, hfa⟩ h
    exact hfa (h (Ideal.mem_map_of_mem f
      (HomogeneousIdeal.mem_irrelevant_of_mem 𝒜 hn ha)))
  · intro h
    by_contra! hnone
    apply h
    rw [imageIrrelevant, Ideal.map_le_iff_le_comap,
      HomogeneousIdeal.irrelevant_eq_span, Ideal.span_le]
    intro a ha
    rcases Set.mem_iUnion.mp ha with ⟨n, hn⟩
    rcases Set.mem_iUnion.mp hn with ⟨hn, ha⟩
    exact hnone ⟨⟨n, hn⟩, ⟨a, ha⟩⟩

/-- Cover of the natural domain by its image distinguished opens. -/
def chartCover (f : A →+* B) : (degreeScaledDomain 𝒜 ℬ f).toScheme.OpenCover :=
  Scheme.Opens.iSupOpenCover (chartOpen 𝒜 ℬ f)

/-- The degree-scaled morphism on one positive homogeneous chart. -/
def degreeScaledChartMap (f : A →+* B) (d : ℕ) (hd : 0 < d)
    (hdeg : ∀ n a, a ∈ 𝒜 n → f a ∈ ℬ (d * n))
    (i : Σ n : PNat, 𝒜 n) :
    (basicOpen ℬ (f (i.2 : A))).toScheme ⟶ Proj 𝒜 :=
  (basicOpenIsoSpec ℬ (f (i.2 : A))
      (hdeg i.1 (i.2 : A) i.2.2) (Nat.mul_pos hd i.1.2)).hom ≫
    Spec.map (CommRingCat.ofHom (Away.mapDegreeMul 𝒜 ℬ f d hdeg (i.2 : A))) ≫
    awayι 𝒜 (i.2 : A) i.2.2 i.1.2

private def chartOverlapIso (f : A →+* B)
    (i j : Σ n : PNat, 𝒜 n) :
    Limits.pullback ((chartCover 𝒜 ℬ f).f i) ((chartCover 𝒜 ℬ f).f j) ≅
      (basicOpen ℬ (f ((i.2 : A) * (j.2 : A)))).toScheme :=
  (isPullback_opens_inf_le
      (X := Proj ℬ) (U := chartOpen 𝒜 ℬ f i) (V := chartOpen 𝒜 ℬ f j)
      (W := degreeScaledDomain 𝒜 ℬ f)
      (le_iSup (chartOpen 𝒜 ℬ f) i) (le_iSup (chartOpen 𝒜 ℬ f) j)).isoPullback.symm ≪≫
    (Proj ℬ).isoOfEq (by
      change basicOpen ℬ (f (i.2 : A)) ⊓ basicOpen ℬ (f (j.2 : A)) =
        basicOpen ℬ (f ((i.2 : A) * (j.2 : A)))
      rw [map_mul, basicOpen_mul])

omit [AddSubgroupClass σ A] [GradedRing 𝒜] in
private theorem imageProduct_mem (f : A →+* B) (d : ℕ)
    (hdeg : ∀ n a, a ∈ 𝒜 n → f a ∈ ℬ (d * n))
    (i j : Σ n : PNat, 𝒜 n) :
    f ((i.2 : A) * (j.2 : A)) ∈ ℬ (d * i.1 + d * j.1) := by
  rw [map_mul]
  exact SetLike.mul_mem_graded
    (hdeg i.1 (i.2 : A) i.2.2) (hdeg j.1 (j.2 : A) j.2.2)

private def chartOverlapSpecIso (f : A →+* B) (d : ℕ) (hd : 0 < d)
    (hdeg : ∀ n a, a ∈ 𝒜 n → f a ∈ ℬ (d * n))
    (i j : Σ n : PNat, 𝒜 n) :
    Limits.pullback ((chartCover 𝒜 ℬ f).f i) ((chartCover 𝒜 ℬ f).f j) ≅
      Spec ↧(Away ℬ (f ((i.2 : A) * (j.2 : A)))) :=
  chartOverlapIso 𝒜 ℬ f i j ≪≫
    basicOpenIsoSpec ℬ (f ((i.2 : A) * (j.2 : A)))
      (imageProduct_mem 𝒜 ℬ f d hdeg i j)
      (Nat.add_pos_left (Nat.mul_pos hd i.1.2) (d * j.1))

private theorem mapDegreeMul_awayMap_right (f : A →+* B) (d : ℕ)
    (hdeg : ∀ n a, a ∈ 𝒜 n → f a ∈ ℬ (d * n))
    {m : ℕ} (a b x : A) (ha : a ∈ 𝒜 m) (hx : x = b * a) :
    (Away.mapDegreeMul 𝒜 ℬ f d hdeg x).comp
      (awayMap 𝒜 ha hx) =
      (awayMap ℬ (hdeg m a ha) (by simp [hx, map_mul])).comp
        (Away.mapDegreeMul 𝒜 ℬ f d hdeg b) := by
  subst x
  exact Away.mapDegreeMul_awayMap 𝒜 ℬ f d hdeg b a ha

set_option backward.isDefEq.respectTransparency false in
omit [AddSubgroupClass σ A] [GradedRing 𝒜] in
private theorem chartOverlapIso_inv_fst (f : A →+* B)
    (i j : Σ n : PNat, 𝒜 n) :
    (chartOverlapIso 𝒜 ℬ f i j).inv ≫
      Limits.pullback.fst ((chartCover 𝒜 ℬ f).f i) ((chartCover 𝒜 ℬ f).f j) =
      (Proj ℬ).homOfLE (show basicOpen ℬ (f ((i.2 : A) * (j.2 : A))) ≤
          basicOpen ℬ (f (i.2 : A)) by
        rw [map_mul, basicOpen_mul]
        exact inf_le_left) := by
  dsimp only [chartOverlapIso, chartCover, Scheme.Opens.iSupOpenCover,
    chartOpen, degreeScaledDomain]
  rw [Iso.trans_inv, Iso.symm_inv, Category.assoc,
    IsPullback.isoPullback_hom_fst, Scheme.isoOfEq_inv, Scheme.homOfLE_homOfLE]

set_option backward.isDefEq.respectTransparency false in
omit [AddSubgroupClass σ A] [GradedRing 𝒜] in
private theorem chartOverlapIso_inv_snd (f : A →+* B)
    (i j : Σ n : PNat, 𝒜 n) :
    (chartOverlapIso 𝒜 ℬ f i j).inv ≫
      Limits.pullback.snd ((chartCover 𝒜 ℬ f).f i) ((chartCover 𝒜 ℬ f).f j) =
      (Proj ℬ).homOfLE (show basicOpen ℬ (f ((i.2 : A) * (j.2 : A))) ≤
          basicOpen ℬ (f (j.2 : A)) by
        rw [map_mul, basicOpen_mul]
        exact inf_le_right) := by
  dsimp only [chartOverlapIso, chartCover, Scheme.Opens.iSupOpenCover,
    chartOpen, degreeScaledDomain]
  rw [Iso.trans_inv, Iso.symm_inv, Category.assoc,
    IsPullback.isoPullback_hom_snd, Scheme.isoOfEq_inv, Scheme.homOfLE_homOfLE]

omit [AddSubgroupClass σ A] [GradedRing 𝒜] in
private theorem productSpec_to_chart_left (f : A →+* B) (d : ℕ) (hd : 0 < d)
    (hdeg : ∀ n a, a ∈ 𝒜 n → f a ∈ ℬ (d * n))
    (i j : Σ n : PNat, 𝒜 n) :
    (basicOpenIsoSpec ℬ (f ((i.2 : A) * (j.2 : A)))
      (imageProduct_mem 𝒜 ℬ f d hdeg i j)
      (Nat.add_pos_left (Nat.mul_pos hd i.1.2) (d * j.1))).inv ≫
      (Proj ℬ).homOfLE (show basicOpen ℬ (f ((i.2 : A) * (j.2 : A))) ≤
        basicOpen ℬ (f (i.2 : A)) by
          rw [map_mul, basicOpen_mul]
          exact inf_le_left) =
    Spec.map (CommRingCat.ofHom (awayMap ℬ (hdeg j.1 (j.2 : A) j.2.2)
        (show f ((i.2 : A) * (j.2 : A)) = f (i.2 : A) * f (j.2 : A) by
          rw [map_mul]))) ≫
      (basicOpenIsoSpec ℬ (f (i.2 : A))
        (hdeg i.1 (i.2 : A) i.2.2) (Nat.mul_pos hd i.1.2)).inv := by
  rw [← cancel_mono (basicOpen ℬ (f (i.2 : A))).ι]
  simp only [Category.assoc, Scheme.homOfLE_ι, basicOpenIsoSpec_inv_ι]
  exact (SpecMap_awayMap_awayι ℬ
    (hdeg i.1 (i.2 : A) i.2.2) (Nat.mul_pos hd i.1.2)
    (hdeg j.1 (j.2 : A) j.2.2) (by rw [map_mul])).symm

private theorem awayι_eq_of_degrees (b : B) {m n : ℕ}
    (hm : b ∈ ℬ m) (hn : b ∈ ℬ n) (hmp : 0 < m) (hnp : 0 < n) :
    awayι ℬ b hm hmp = awayι ℬ b hn hnp := by
  have heq : basicOpenIsoSpec ℬ b hm hmp = basicOpenIsoSpec ℬ b hn hnp :=
    Iso.ext (by rw [basicOpenIsoSpec_hom, basicOpenIsoSpec_hom])
  simp only [awayι, heq]

omit [AddSubgroupClass σ A] [GradedRing 𝒜] in
private theorem productSpec_to_chart_right (f : A →+* B) (d : ℕ) (hd : 0 < d)
    (hdeg : ∀ n a, a ∈ 𝒜 n → f a ∈ ℬ (d * n))
    (i j : Σ n : PNat, 𝒜 n) :
    (basicOpenIsoSpec ℬ (f ((i.2 : A) * (j.2 : A)))
      (imageProduct_mem 𝒜 ℬ f d hdeg i j)
      (Nat.add_pos_left (Nat.mul_pos hd i.1.2) (d * j.1))).inv ≫
      (Proj ℬ).homOfLE (show basicOpen ℬ (f ((i.2 : A) * (j.2 : A))) ≤
        basicOpen ℬ (f (j.2 : A)) by
          rw [map_mul, basicOpen_mul]
          exact inf_le_right) =
    Spec.map (CommRingCat.ofHom (awayMap ℬ (hdeg i.1 (i.2 : A) i.2.2)
        (show f ((i.2 : A) * (j.2 : A)) = f (j.2 : A) * f (i.2 : A) by
          rw [map_mul]
          exact mul_comm _ _))) ≫
      (basicOpenIsoSpec ℬ (f (j.2 : A))
        (hdeg j.1 (j.2 : A) j.2.2) (Nat.mul_pos hd j.1.2)).inv := by
  have hreverse : f ((i.2 : A) * (j.2 : A)) ∈ ℬ (d * j.1 + d * i.1) := by
    rw [map_mul, mul_comm (f (i.2 : A)) (f (j.2 : A))]
    exact SetLike.mul_mem_graded
      (hdeg j.1 (j.2 : A) j.2.2) (hdeg i.1 (i.2 : A) i.2.2)
  rw [← cancel_mono (basicOpen ℬ (f (j.2 : A))).ι]
  simp only [Category.assoc, Scheme.homOfLE_ι, basicOpenIsoSpec_inv_ι]
  calc
    awayι ℬ (f ((i.2 : A) * (j.2 : A)))
        (imageProduct_mem 𝒜 ℬ f d hdeg i j)
        (Nat.add_pos_left (Nat.mul_pos hd i.1.2) (d * j.1)) =
      awayι ℬ (f ((i.2 : A) * (j.2 : A))) hreverse
        (Nat.add_pos_left (Nat.mul_pos hd j.1.2) (d * i.1)) :=
          awayι_eq_of_degrees ℬ _ _ _ _ _
    _ = _ := (SpecMap_awayMap_awayι ℬ
      (hdeg j.1 (j.2 : A) j.2.2) (Nat.mul_pos hd j.1.2)
      (hdeg i.1 (i.2 : A) i.2.2) (by
        rw [map_mul]
        exact mul_comm _ _)).symm

set_option backward.isDefEq.respectTransparency false in
omit [AddSubgroupClass σ A] [GradedRing 𝒜] in
private theorem chartOverlapSpecIso_inv_fst (f : A →+* B) (d : ℕ) (hd : 0 < d)
    (hdeg : ∀ n a, a ∈ 𝒜 n → f a ∈ ℬ (d * n))
    (i j : Σ n : PNat, 𝒜 n) :
    (chartOverlapSpecIso 𝒜 ℬ f d hd hdeg i j).inv ≫
      Limits.pullback.fst ((chartCover 𝒜 ℬ f).f i) ((chartCover 𝒜 ℬ f).f j) =
      Spec.map (CommRingCat.ofHom (awayMap ℬ (hdeg j.1 (j.2 : A) j.2.2)
          (show f ((i.2 : A) * (j.2 : A)) = f (i.2 : A) * f (j.2 : A) by
            rw [map_mul]))) ≫
        (basicOpenIsoSpec ℬ (f (i.2 : A))
          (hdeg i.1 (i.2 : A) i.2.2) (Nat.mul_pos hd i.1.2)).inv := by
  unfold chartOverlapSpecIso
  rw [Iso.trans_inv, Category.assoc, chartOverlapIso_inv_fst,
    productSpec_to_chart_left]; exact hd

set_option backward.isDefEq.respectTransparency false in
omit [AddSubgroupClass σ A] [GradedRing 𝒜] in
private theorem chartOverlapSpecIso_inv_snd (f : A →+* B) (d : ℕ) (hd : 0 < d)
    (hdeg : ∀ n a, a ∈ 𝒜 n → f a ∈ ℬ (d * n))
    (i j : Σ n : PNat, 𝒜 n) :
    (chartOverlapSpecIso 𝒜 ℬ f d hd hdeg i j).inv ≫
      Limits.pullback.snd ((chartCover 𝒜 ℬ f).f i) ((chartCover 𝒜 ℬ f).f j) =
      Spec.map (CommRingCat.ofHom (awayMap ℬ (hdeg i.1 (i.2 : A) i.2.2)
          (show f ((i.2 : A) * (j.2 : A)) = f (j.2 : A) * f (i.2 : A) by
            rw [map_mul]
            exact mul_comm _ _))) ≫
        (basicOpenIsoSpec ℬ (f (j.2 : A))
          (hdeg j.1 (j.2 : A) j.2.2) (Nat.mul_pos hd j.1.2)).inv := by
  unfold chartOverlapSpecIso
  rw [Iso.trans_inv, Category.assoc, chartOverlapIso_inv_snd,
    productSpec_to_chart_right]; exact hd

set_option backward.isDefEq.respectTransparency false in
/-- Degree-scaled chart arrows agree on both faces of every cover overlap. -/
theorem degreeScaledChartMap_compatible (f : A →+* B) (d : ℕ) (hd : 0 < d)
    (hdeg : ∀ n a, a ∈ 𝒜 n → f a ∈ ℬ (d * n))
    (i j : Σ n : PNat, 𝒜 n) :
    Limits.pullback.fst ((chartCover 𝒜 ℬ f).f i) ((chartCover 𝒜 ℬ f).f j) ≫
      degreeScaledChartMap 𝒜 ℬ f d hd hdeg i =
    Limits.pullback.snd ((chartCover 𝒜 ℬ f).f i) ((chartCover 𝒜 ℬ f).f j) ≫
      degreeScaledChartMap 𝒜 ℬ f d hd hdeg j := by
  let e := chartOverlapSpecIso 𝒜 ℬ f d hd hdeg i j
  rw [← cancel_epi e.inv]
  dsimp only [e]
  rw [← Category.assoc, ← Category.assoc,
    chartOverlapSpecIso_inv_fst, chartOverlapSpecIso_inv_snd]
  simp only [degreeScaledChartMap, Category.assoc, Iso.inv_hom_id_assoc]
  rw [← Category.assoc, ← Category.assoc, ← Spec.map_comp, ← Spec.map_comp,
    ← CommRingCat.ofHom_comp, ← CommRingCat.ofHom_comp]
  rw [← Away.mapDegreeMul_awayMap 𝒜 ℬ f d hdeg
    (i.2 : A) (j.2 : A) j.2.2]
  rw [← mapDegreeMul_awayMap_right 𝒜 ℬ f d hdeg
    (i.2 : A) (j.2 : A) ((i.2 : A) * (j.2 : A)) i.2.2 (mul_comm _ _)]
  simp only [CommRingCat.ofHom_comp, Spec.map_comp, Category.assoc]
  rw [SpecMap_awayMap_awayι 𝒜 i.2.2 i.1.2 j.2.2 rfl,
    SpecMap_awayMap_awayι 𝒜 j.2.2 j.1.2 i.2.2 (mul_comm _ _)]
  congr 1

/-- The scheme morphism induced by a positive-degree-scaled ring map on its natural open domain. -/
def degreeScaledMap (f : A →+* B) (d : ℕ) (hd : 0 < d)
    (hdeg : ∀ n a, a ∈ 𝒜 n → f a ∈ ℬ (d * n)) :
    (degreeScaledDomain 𝒜 ℬ f).toScheme ⟶ Proj 𝒜 :=
  (chartCover 𝒜 ℬ f).glueMorphisms
    (degreeScaledChartMap 𝒜 ℬ f d hd hdeg)
    (degreeScaledChartMap_compatible 𝒜 ℬ f d hd hdeg)

/-- On each image distinguished open, the glued scheme arrow is the degree-scaled chart arrow. -/
theorem chartCover_map (f : A →+* B) (d : ℕ) (hd : 0 < d)
    (hdeg : ∀ n a, a ∈ 𝒜 n → f a ∈ ℬ (d * n))
    (i : Σ n : PNat, 𝒜 n) :
    (chartCover 𝒜 ℬ f).f i ≫ degreeScaledMap 𝒜 ℬ f d hd hdeg =
      degreeScaledChartMap 𝒜 ℬ f d hd hdeg i :=
  (chartCover 𝒜 ℬ f).ι_glueMorphisms _ _ i

set_option backward.isDefEq.respectTransparency.types false in
/-- Whole-affine-chart computation, including the structure-sheaf map on fractions. -/
theorem degreeScaledMap_chartSpec (f : A →+* B) (d : ℕ) (hd : 0 < d)
    (hdeg : ∀ n a, a ∈ 𝒜 n → f a ∈ ℬ (d * n))
    (i : Σ n : PNat, 𝒜 n) :
    (basicOpenIsoSpec ℬ (f (i.2 : A))
      (hdeg i.1 (i.2 : A) i.2.2) (Nat.mul_pos hd i.1.2)).inv ≫
        (chartCover 𝒜 ℬ f).f i ≫ degreeScaledMap 𝒜 ℬ f d hd hdeg =
      Spec.map (CommRingCat.ofHom (Away.mapDegreeMul 𝒜 ℬ f d hdeg (i.2 : A))) ≫
        awayι 𝒜 (i.2 : A) i.2.2 i.1.2 := by
  calc
    _ = (basicOpenIsoSpec ℬ (f (i.2 : A))
        (hdeg i.1 (i.2 : A) i.2.2) (Nat.mul_pos hd i.1.2)).inv ≫
          degreeScaledChartMap 𝒜 ℬ f d hd hdeg i := by
            exact (Category.assoc _ _ _).trans (congrArg _ (chartCover_map 𝒜 ℬ f d hd hdeg i))
    _ = _ := by
      unfold degreeScaledChartMap
      simp only [← Category.assoc, Iso.inv_hom_id, Category.id_comp]

/-- The chart law uniquely determines the scheme arrow on the union domain. -/
theorem degreeScaledMap_unique (f : A →+* B) (d : ℕ) (hd : 0 < d)
    (hdeg : ∀ n a, a ∈ 𝒜 n → f a ∈ ℬ (d * n))
    (g : (degreeScaledDomain 𝒜 ℬ f).toScheme ⟶ Proj 𝒜)
    (hg : ∀ i : Σ n : PNat, 𝒜 n,
      (chartCover 𝒜 ℬ f).f i ≫ g = degreeScaledChartMap 𝒜 ℬ f d hd hdeg i) :
    g = degreeScaledMap 𝒜 ℬ f d hd hdeg :=
  (chartCover 𝒜 ℬ f).hom_ext _ _ (fun i => (hg i).trans (chartCover_map 𝒜 ℬ f d hd hdeg i).symm)

/-- The restriction of a degree-scaled map to the degree-zero subrings. -/
def degreeZeroRingHom (f : A →+* B) (d : ℕ)
    (hdeg : ∀ n a, a ∈ 𝒜 n → f a ∈ ℬ (d * n)) : 𝒜 0 →+* ℬ 0 where
  toFun a := ⟨f a, by simpa only [mul_zero] using hdeg 0 a a.2⟩
  map_one' := by apply Subtype.ext; exact map_one f
  map_mul' a b := by apply Subtype.ext; exact map_mul f (a : A) (b : A)
  map_zero' := by apply Subtype.ext; exact map_zero f
  map_add' a b := by apply Subtype.ext; exact map_add f (a : A) (b : A)

private theorem val_fromZeroRingHom (a : A) (z : 𝒜 0) :
    ((fromZeroRingHom 𝒜 (Submonoid.powers a)) z).val =
      algebraMap A (Localization (Submonoid.powers a)) (z : A) := by
  rfl

/-- Restriction of the ordinary coefficient map agrees with the chart-localized map. -/
theorem mapDegreeMul_fromZeroRingHom (f : A →+* B) (d : ℕ)
    (hdeg : ∀ n a, a ∈ 𝒜 n → f a ∈ ℬ (d * n)) (a : A) :
    (Away.mapDegreeMul 𝒜 ℬ f d hdeg a).comp
      (fromZeroRingHom 𝒜 (Submonoid.powers a)) =
      (fromZeroRingHom ℬ (Submonoid.powers (f a))).comp
        (degreeZeroRingHom 𝒜 ℬ f d hdeg) := by
  apply RingHom.ext
  intro z
  apply HomogeneousLocalization.val_injective _
  simp only [RingHom.comp_apply, Away.mapDegreeMul, val_mapDegreeMul,
    val_fromZeroRingHom]
  rw [IsLocalization.map_eq]
  exact (val_fromZeroRingHom ℬ (f a) (degreeZeroRingHom 𝒜 ℬ f d hdeg z)).symm

/-- Degree-zero base naturality on an individual affine image chart. -/
theorem degreeScaledChart_base (f : A →+* B) (d : ℕ) (hd : 0 < d)
    (hdeg : ∀ n a, a ∈ 𝒜 n → f a ∈ ℬ (d * n))
    {m : ℕ} (a : A) (ha : a ∈ 𝒜 m) (hm : 0 < m) :
    Spec.map (CommRingCat.ofHom (Away.mapDegreeMul 𝒜 ℬ f d hdeg a)) ≫
      awayι 𝒜 a ha hm ≫ toSpecZero 𝒜 =
    awayι ℬ (f a) (hdeg m a ha) (Nat.mul_pos hd hm) ≫ toSpecZero ℬ ≫
      Spec.map (CommRingCat.ofHom (degreeZeroRingHom 𝒜 ℬ f d hdeg)) := by
  rw [awayι_toSpecZero 𝒜, ← Category.assoc, awayι_toSpecZero ℬ]
  rw [← Spec.map_comp, ← Spec.map_comp, ← CommRingCat.ofHom_comp,
    ← CommRingCat.ofHom_comp, mapDegreeMul_fromZeroRingHom]

set_option backward.isDefEq.respectTransparency false in
/-- The open-domain map commutes with the degree-zero structure morphisms. -/
theorem degreeScaledMap_toSpecZero (f : A →+* B) (d : ℕ) (hd : 0 < d)
    (hdeg : ∀ n a, a ∈ 𝒜 n → f a ∈ ℬ (d * n)) :
    degreeScaledMap 𝒜 ℬ f d hd hdeg ≫ toSpecZero 𝒜 =
      (degreeScaledDomain 𝒜 ℬ f).ι ≫ toSpecZero ℬ ≫
        Spec.map (CommRingCat.ofHom (degreeZeroRingHom 𝒜 ℬ f d hdeg)) := by
  refine (chartCover 𝒜 ℬ f).hom_ext _ _ fun i => ?_
  rw [← cancel_epi (basicOpenIsoSpec ℬ (f (i.2 : A))
    (hdeg i.1 (i.2 : A) i.2.2) (Nat.mul_pos hd i.1.2)).inv]
  have hcover : (chartCover 𝒜 ℬ f).f i ≫ (degreeScaledDomain 𝒜 ℬ f).ι =
      (basicOpen ℬ (f (i.2 : A))).ι := by
    exact Scheme.homOfLE_ι (Proj ℬ) (le_iSup (chartOpen 𝒜 ℬ f) i)
  calc
    _ = Spec.map (CommRingCat.ofHom (Away.mapDegreeMul 𝒜 ℬ f d hdeg (i.2 : A))) ≫
        awayι 𝒜 (i.2 : A) i.2.2 i.1.2 ≫ toSpecZero 𝒜 := by
          simpa only [Category.assoc] using congrArg (· ≫ toSpecZero 𝒜)
            (degreeScaledMap_chartSpec 𝒜 ℬ f d hd hdeg i)
    _ = awayι ℬ (f (i.2 : A)) (hdeg i.1 (i.2 : A) i.2.2)
          (Nat.mul_pos hd i.1.2) ≫ toSpecZero ℬ ≫
            Spec.map (CommRingCat.ofHom (degreeZeroRingHom 𝒜 ℬ f d hdeg)) :=
              degreeScaledChart_base 𝒜 ℬ f d hd hdeg (i.2 : A) i.2.2 i.1.2
    _ = _ := by
      have hchartι :
          (basicOpenIsoSpec ℬ (f (i.2 : A))
            (hdeg i.1 (i.2 : A) i.2.2) (Nat.mul_pos hd i.1.2)).inv ≫
              (chartCover 𝒜 ℬ f).f i ≫ (degreeScaledDomain 𝒜 ℬ f).ι =
                awayι ℬ (f (i.2 : A))
                  (hdeg i.1 (i.2 : A) i.2.2) (Nat.mul_pos hd i.1.2) := by
        calc
          _ = (basicOpenIsoSpec ℬ (f (i.2 : A))
              (hdeg i.1 (i.2 : A) i.2.2) (Nat.mul_pos hd i.1.2)).inv ≫
                ((chartCover 𝒜 ℬ f).f i ≫ (degreeScaledDomain 𝒜 ℬ f).ι) :=
                  Category.assoc _ _ _
          _ = (basicOpenIsoSpec ℬ (f (i.2 : A))
              (hdeg i.1 (i.2 : A) i.2.2) (Nat.mul_pos hd i.1.2)).inv ≫
                (basicOpen ℬ (f (i.2 : A))).ι := congrArg _ hcover
          _ = _ := basicOpenIsoSpec_inv_ι ℬ _ _ _
      simpa only [Category.assoc] using
        (congrArg (fun q => q ≫ toSpecZero ℬ ≫
          Spec.map (CommRingCat.ofHom (degreeZeroRingHom 𝒜 ℬ f d hdeg))) hchartι).symm

/-- Scaling the source chart parameter yields the target chart parameter after a positive power. -/
theorem mapDegreeMul_isLocalizationElem_pow (f : A →+* B) (d : ℕ)
    (hdeg : ∀ n a, a ∈ 𝒜 n → f a ∈ ℬ (d * n))
    {m n : ℕ} (a r : A) (ha : a ∈ 𝒜 m) (hr : r ∈ 𝒜 n) :
    Away.mapDegreeMul 𝒜 ℬ f d hdeg a (Away.isLocalizationElem ha hr) ^ d =
      Away.isLocalizationElem (hdeg m a ha) (hdeg n r hr) := by
  apply HomogeneousLocalization.val_injective _
  simp only [Away.mapDegreeMul, val_pow, val_mapDegreeMul,
    Away.isLocalizationElem, Away.val_mk]
  rw [Localization.mk_eq_mk'_apply, IsLocalization.map_mk']
  simp only [← Localization.mk_eq_mk', map_pow, Localization.mk_pow, pow_mul]
  congr 1
  · rw [← pow_mul, ← pow_mul, mul_comm m d]
  · apply Subtype.ext
    simp only [SubmonoidClass.coe_pow]
    rw [← pow_mul, ← pow_mul, mul_comm n d]

/-- On a source affine chart, arbitrary positive basic opens pull back to image basic opens. -/
theorem degreeScaledChartSpec_preimage_basicOpen (f : A →+* B) (d : ℕ) (hd : 0 < d)
    (hdeg : ∀ n a, a ∈ 𝒜 n → f a ∈ ℬ (d * n))
    (i : Σ m : PNat, 𝒜 m) {n : ℕ} (r : A) (hr : r ∈ 𝒜 n) (hn : 0 < n) :
    (Spec.map (CommRingCat.ofHom (Away.mapDegreeMul 𝒜 ℬ f d hdeg (i.2 : A))) ≫
      awayι 𝒜 (i.2 : A) i.2.2 i.1.2) ⁻¹ᵁ basicOpen 𝒜 r =
      (awayι ℬ (f (i.2 : A)) (hdeg i.1 (i.2 : A) i.2.2)
        (Nat.mul_pos hd i.1.2)) ⁻¹ᵁ basicOpen ℬ (f r) := by
  rw [Scheme.Hom.comp_preimage,
    awayι_preimage_basicOpen 𝒜 i.2.2 i.1.2 hr hn,
    awayι_preimage_basicOpen ℬ (hdeg i.1 (i.2 : A) i.2.2)
      (Nat.mul_pos hd i.1.2) (hdeg n r hr) (Nat.mul_pos hd hn),
    SpecMap_preimage_basicOpen]
  change PrimeSpectrum.basicOpen
      (Away.mapDegreeMul 𝒜 ℬ f d hdeg (i.2 : A) (Away.isLocalizationElem i.2.2 hr)) =
    PrimeSpectrum.basicOpen
      (Away.isLocalizationElem (hdeg i.1 (i.2 : A) i.2.2) (hdeg n r hr))
  rw [← PrimeSpectrum.basicOpen_pow
    ((Away.mapDegreeMul 𝒜 ℬ f d hdeg (i.2 : A))
      (Away.isLocalizationElem i.2.2 hr)) d hd,
    mapDegreeMul_isLocalizationElem_pow 𝒜 ℬ f d hdeg (i.2 : A) r i.2.2 hr]

set_option backward.isDefEq.respectTransparency.types false in
/-- The chart scheme arrow has the expected preimage for any positive homogeneous form. -/
theorem degreeScaledChartMap_preimage_basicOpen (f : A →+* B) (d : ℕ) (hd : 0 < d)
    (hdeg : ∀ n a, a ∈ 𝒜 n → f a ∈ ℬ (d * n))
    (i : Σ m : PNat, 𝒜 m) {n : ℕ} (r : A) (hr : r ∈ 𝒜 n) (hn : 0 < n) :
    (degreeScaledChartMap 𝒜 ℬ f d hd hdeg i) ⁻¹ᵁ basicOpen 𝒜 r =
      (basicOpen ℬ (f (i.2 : A))).ι ⁻¹ᵁ basicOpen ℬ (f r) := by
  ext x
  obtain ⟨y, rfl⟩ := (basicOpenIsoSpec ℬ (f (i.2 : A))
    (hdeg i.1 (i.2 : A) i.2.2) (Nat.mul_pos hd i.1.2)).inv.homeomorph.surjective x
  have hh := congrArg (fun V : (Spec ↧(Away ℬ (f (i.2 : A)))).Opens => y ∈ V)
    (degreeScaledChartSpec_preimage_basicOpen 𝒜 ℬ f d hd hdeg i r hr hn)
  simpa only [Scheme.Hom.homeomorph_apply, SetLike.mem_coe,
    Scheme.Hom.mem_preimage,
    ← Scheme.Hom.comp_apply,
    degreeScaledChartMap, Category.assoc, Iso.inv_hom_id_assoc,
    Category.id_comp, basicOpenIsoSpec_inv_ι] using hh.to_iff

/-- A positive target basic open pulls back to its image basic open within the union domain. -/
theorem degreeScaledMap_preimage_basicOpen (f : A →+* B) (d : ℕ) (hd : 0 < d)
    (hdeg : ∀ n a, a ∈ 𝒜 n → f a ∈ ℬ (d * n))
    {n : ℕ} (r : A) (hr : r ∈ 𝒜 n) (hn : 0 < n) :
    degreeScaledMap 𝒜 ℬ f d hd hdeg ⁻¹ᵁ basicOpen 𝒜 r =
      (degreeScaledDomain 𝒜 ℬ f).ι ⁻¹ᵁ basicOpen ℬ (f r) := by
  ext x
  obtain ⟨i, y, rfl⟩ := (chartCover 𝒜 ℬ f).exists_eq x
  have hcover : (chartCover 𝒜 ℬ f).f i ≫ (degreeScaledDomain 𝒜 ℬ f).ι =
      (basicOpen ℬ (f (i.2 : A))).ι :=
    Scheme.homOfLE_ι (Proj ℬ) (le_iSup (chartOpen 𝒜 ℬ f) i)
  have hh := congrArg (fun V : (basicOpen ℬ (f (i.2 : A))).toScheme.Opens => y ∈ V)
    (degreeScaledChartMap_preimage_basicOpen 𝒜 ℬ f d hd hdeg i r hr hn)
  have hchart : (degreeScaledChartMap 𝒜 ℬ f d hd hdeg i y ∈ basicOpen 𝒜 r) ↔
      ((basicOpen ℬ (f (i.2 : A))).ι y ∈ basicOpen ℬ (f r)) := by
    constructor
    · intro hy
      apply (Scheme.Hom.mem_preimage (f := (basicOpen ℬ (f (i.2 : A))).ι)).mp
      apply hh.to_iff.mp
      exact (Scheme.Hom.mem_preimage (f := degreeScaledChartMap 𝒜 ℬ f d hd hdeg i)).mpr hy
    · intro hy
      apply (Scheme.Hom.mem_preimage (f := degreeScaledChartMap 𝒜 ℬ f d hd hdeg i)).mp
      apply hh.to_iff.mpr
      exact (Scheme.Hom.mem_preimage (f := (basicOpen ℬ (f (i.2 : A))).ι)).mpr hy
  constructor
  · intro hy
    have htarget : ((chartCover 𝒜 ℬ f).f i ≫ degreeScaledMap 𝒜 ℬ f d hd hdeg) y ∈
        basicOpen 𝒜 r := (Scheme.Hom.mem_preimage
          (f := degreeScaledMap 𝒜 ℬ f d hd hdeg)).mp hy
    rw [chartCover_map 𝒜 ℬ f d hd hdeg i] at htarget
    apply (Scheme.Hom.mem_preimage (f := (degreeScaledDomain 𝒜 ℬ f).ι)).mpr
    rw [← Scheme.Hom.comp_apply, hcover]
    exact hchart.mp htarget
  · intro hy
    have htarget : ((chartCover 𝒜 ℬ f).f i ≫ (degreeScaledDomain 𝒜 ℬ f).ι) y ∈
        basicOpen ℬ (f r) := (Scheme.Hom.mem_preimage
          (f := (degreeScaledDomain 𝒜 ℬ f).ι)).mp hy
    rw [hcover] at htarget
    apply (Scheme.Hom.mem_preimage (f := degreeScaledMap 𝒜 ℬ f d hd hdeg)).mpr
    rw [← Scheme.Hom.comp_apply, chartCover_map 𝒜 ℬ f d hd hdeg i]
    exact hchart.mpr htarget

end AlgebraicGeometry.Proj
