/-
SPDX-License-Identifier: Apache-2.0
Authors: Formal Frontier Agents
-/

module

public import ProjectiveSpace.HypersurfaceChart

/-!
# Homogeneous systems of equations on projective standard charts

This file packages the dehomogenized ideals attached to a family of
homogeneous polynomials. It shows that the standard chart transition carries
the localized ideal from one chart to the localized ideal from the other.
-/

public section

noncomputable section

open HomogeneousLocalization
open scoped ProjectiveSpace

namespace ProjectiveSpace

universe u v w

variable (R : Type u) [CommRing R]
variable (ι : Type v) (i : ι)

/-- Classical coordinate equality, scoped to the homogeneous-ideal chart module. -/
local instance instDecidableEqHomogeneousIdealCoordinates : DecidableEq ι := Classical.decEq ι

local notation "Others" => {j : ι // j ≠ i}
local notation "Poly" => MvPolynomial ι R
local notation "Q" => MvPolynomial Others R
local notation "𝒜" => MvPolynomial.homogeneousSubmodule ι R

/-- The ideal generated by the dehomogenizations of a homogeneous family on
the `i`th standard chart. -/
@[expose] def dehomogenizedIdeal [Fintype ι] (κ : Type w) (d : κ → ℕ)
    (F : κ → Poly) (hF : ∀ a, F a ∈ 𝒜 (d a)) : Ideal Q :=
  Ideal.span (Set.range fun a => dehomogenizedPolynomial R ι i (F a) (hF a))

/-- The affine coordinate ring cut out by a homogeneous family on the `i`th
standard chart. -/
abbrev StandardChartHomogeneousIdeal [Fintype ι] (κ : Type w) (d : κ → ℕ)
    (F : κ → Poly) (hF : ∀ a, F a ∈ 𝒜 (d a)) :=
  Q ⧸ dehomogenizedIdeal R ι i κ d F hF

/-- The `i`th dehomogenized ideal after restriction to the overlap with the
`j`th chart. -/
@[expose] def localizedDehomogenizedIdeal [Fintype ι] (j : Others) (κ : Type w)
    (d : κ → ℕ) (F : κ → Poly) (hF : ∀ a, F a ∈ 𝒜 (d a)) :
    Ideal (StandardChartPolynomialOverlap R ι i j) :=
  Ideal.span (Set.range fun a =>
    localizedDehomogenizedPolynomial R ι i j (F a) (hF a))

/-- The `j`th dehomogenized ideal after restriction to the overlap with the
`i`th chart, in the right polynomial presentation. -/
@[expose] def localizedDehomogenizedIdealRight [Fintype ι] (j : Others) (κ : Type w)
    (d : κ → ℕ) (F : κ → Poly) (hF : ∀ a, F a ∈ 𝒜 (d a)) :
    Ideal (StandardChartPolynomialOverlapRight R ι i j) :=
  Ideal.span (Set.range fun a =>
    localizedDehomogenizedPolynomialRight R ι i j (F a) (hF a))

/-- Restricting the chart ideal to an overlap gives the ideal generated by the
localized dehomogenized equations. -/
theorem map_dehomogenizedIdeal [Fintype ι] (j : Others) (κ : Type w)
    (d : κ → ℕ) (F : κ → Poly) (hF : ∀ a, F a ∈ 𝒜 (d a)) :
    Ideal.map (algebraMap Q (StandardChartPolynomialOverlap R ι i j))
        (dehomogenizedIdeal R ι i κ d F hF) =
      localizedDehomogenizedIdeal R ι i j κ d F hF := by
  rw [dehomogenizedIdeal, localizedDehomogenizedIdeal, Ideal.map_span]
  congr 1
  ext x
  constructor
  · rintro ⟨_, ⟨a, rfl⟩, rfl⟩
    exact ⟨a, rfl⟩
  · rintro ⟨a, rfl⟩
    exact ⟨_, ⟨a, rfl⟩, rfl⟩

/-- Restricting the other chart's ideal to the same overlap gives the ideal
generated by its localized dehomogenized equations. -/
theorem map_dehomogenizedIdealRight [Fintype ι] (j : Others) (κ : Type w)
    (d : κ → ℕ) (F : κ → Poly) (hF : ∀ a, F a ∈ 𝒜 (d a)) :
    Ideal.map
        (algebraMap (MvPolynomial {k : ι // k ≠ j.1} R)
          (StandardChartPolynomialOverlapRight R ι i j))
        (dehomogenizedIdeal R ι j.1 κ d F hF) =
      localizedDehomogenizedIdealRight R ι i j κ d F hF := by
  rw [dehomogenizedIdeal, localizedDehomogenizedIdealRight, Ideal.map_span]
  congr 1
  ext x
  constructor
  · rintro ⟨_, ⟨a, rfl⟩, rfl⟩
    exact ⟨a, rfl⟩
  · rintro ⟨a, rfl⟩
    exact ⟨_, ⟨a, rfl⟩, rfl⟩

private theorem span_range_mul_isUnit_eq {S : Type*} [CommSemiring S]
    {κ : Type*} (f u : κ → S) (hu : ∀ a, IsUnit (u a)) :
    Ideal.span (Set.range fun a => f a * u a) = Ideal.span (Set.range f) := by
  apply le_antisymm
  · refine Ideal.span_le.2 ?_
    rintro _ ⟨a, rfl⟩
    exact (Ideal.span (Set.range f)).mul_mem_right _
      (Ideal.subset_span (Set.mem_range_self a))
  · refine Ideal.span_le.2 ?_
    rintro _ ⟨a, rfl⟩
    apply (Ideal.mul_unit_mem_iff_mem _ (hu a)).mp
    exact Ideal.subset_span (Set.mem_range_self a)

/-- Standard polynomial transition carries the localized ideal generated by
an arbitrary homogeneous family to the corresponding ideal on the other
chart. -/
theorem standardChartPolynomialTransition_map_localizedDehomogenizedIdeal
    [Fintype ι] (j : Others) (κ : Type w) (d : κ → ℕ) (F : κ → Poly)
    (hF : ∀ a, F a ∈ 𝒜 (d a)) :
    Ideal.map (standardChartPolynomialTransition R ι i j :
        StandardChartPolynomialOverlap R ι i j →+*
          StandardChartPolynomialOverlapRight R ι i j)
        (localizedDehomogenizedIdeal R ι i j κ d F hF) =
      localizedDehomogenizedIdealRight R ι i j κ d F hF := by
  rw [localizedDehomogenizedIdeal, localizedDehomogenizedIdealRight,
    Ideal.map_span]
  have hrange :
      ((standardChartPolynomialTransition R ι i j :
          StandardChartPolynomialOverlap R ι i j →+*
            StandardChartPolynomialOverlapRight R ι i j) :
          StandardChartPolynomialOverlap R ι i j →
            StandardChartPolynomialOverlapRight R ι i j) ''
          Set.range (fun a =>
            localizedDehomogenizedPolynomial R ι i j (F a) (hF a)) =
        Set.range (fun a =>
          standardChartPolynomialTransition R ι i j
            (localizedDehomogenizedPolynomial R ι i j (F a) (hF a))) := by
    ext x
    constructor
    · rintro ⟨_, ⟨a, rfl⟩, rfl⟩
      exact ⟨a, rfl⟩
    · rintro ⟨a, rfl⟩
      exact ⟨_, ⟨a, rfl⟩, rfl⟩
  rw [hrange]
  simp_rw [standardChartPolynomialTransition_localizedDehomogenizedPolynomial]
  exact span_range_mul_isUnit_eq _ _ fun a =>
    (isUnit_standardChartPolynomialTransitionUnit R ι i j).pow (d a)

/-- The two localized affine presentations cut out by a homogeneous family
agree on a standard-chart overlap. -/
noncomputable def standardChartHomogeneousIdealOverlapEquiv [Fintype ι]
    (j : Others) (κ : Type w) (d : κ → ℕ) (F : κ → Poly)
    (hF : ∀ a, F a ∈ 𝒜 (d a)) :
    (StandardChartPolynomialOverlap R ι i j ⧸
        localizedDehomogenizedIdeal R ι i j κ d F hF) ≃ₐ[R]
      (StandardChartPolynomialOverlapRight R ι i j ⧸
        localizedDehomogenizedIdealRight R ι i j κ d F hF) :=
  Ideal.quotientEquivAlg _ _ (standardChartPolynomialTransition R ι i j)
    (standardChartPolynomialTransition_map_localizedDehomogenizedIdeal
      R ι i j κ d F hF).symm

@[simp]
theorem standardChartHomogeneousIdealOverlapEquiv_mk [Fintype ι]
    (j : Others) (κ : Type w) (d : κ → ℕ) (F : κ → Poly)
    (hF : ∀ a, F a ∈ 𝒜 (d a))
    (x : StandardChartPolynomialOverlap R ι i j) :
    standardChartHomogeneousIdealOverlapEquiv R ι i j κ d F hF
        (Ideal.Quotient.mk _ x) =
      Ideal.Quotient.mk _ (standardChartPolynomialTransition R ι i j x) := by
  apply Ideal.quotientEquivAlg_mk

@[simp]
theorem standardChartHomogeneousIdealOverlapEquiv_coordinate_self [Fintype ι]
    (j : Others) (κ : Type w) (d : κ → ℕ) (F : κ → Poly)
    (hF : ∀ a, F a ∈ 𝒜 (d a)) :
    standardChartHomogeneousIdealOverlapEquiv R ι i j κ d F hF
        (algebraMap Q
          (StandardChartPolynomialOverlap R ι i j ⧸
            localizedDehomogenizedIdeal R ι i j κ d F hF)
          (MvPolynomial.X j)) =
      Ideal.Quotient.mk _
        (standardChartPolynomialTransitionUnit R ι i j) := by
  change standardChartHomogeneousIdealOverlapEquiv R ι i j κ d F hF
      (Ideal.Quotient.mk _
        (algebraMap Q (StandardChartPolynomialOverlap R ι i j)
          (MvPolynomial.X j))) = _
  rw [standardChartHomogeneousIdealOverlapEquiv_mk,
    standardChartPolynomialTransition_self]

theorem standardChartHomogeneousIdealOverlap_transitionUnit_mul_variable
    [Fintype ι] (j : Others) (κ : Type w) (d : κ → ℕ) (F : κ → Poly)
    (hF : ∀ a, F a ∈ 𝒜 (d a)) :
    Ideal.Quotient.mk (localizedDehomogenizedIdealRight R ι i j κ d F hF)
          (standardChartPolynomialTransitionUnit R ι i j) *
        Ideal.Quotient.mk (localizedDehomogenizedIdealRight R ι i j κ d F hF)
          (algebraMap (MvPolynomial {k : ι // k ≠ j.1} R)
            (StandardChartPolynomialOverlapRight R ι i j)
            (MvPolynomial.X ⟨i, Ne.symm j.2⟩)) = 1 := by
  rw [← map_mul, standardChartPolynomialTransitionUnit_mul_variable,
    map_one]

theorem standardChartHomogeneousIdealOverlapEquiv_coordinate_other [Fintype ι]
    (j : Others) (κ : Type w) (d : κ → ℕ) (F : κ → Poly)
    (hF : ∀ a, F a ∈ 𝒜 (d a)) (k : ι) (hki : k ≠ i) (hkj : k ≠ j.1) :
    standardChartHomogeneousIdealOverlapEquiv R ι i j κ d F hF
        (Ideal.Quotient.mk _
          (algebraMap Q (StandardChartPolynomialOverlap R ι i j)
            (MvPolynomial.X ⟨k, hki⟩))) =
      Ideal.Quotient.mk _
          (algebraMap (MvPolynomial {l : ι // l ≠ j.1} R)
            (StandardChartPolynomialOverlapRight R ι i j)
            (MvPolynomial.X ⟨k, hkj⟩)) *
        Ideal.Quotient.mk _
          (standardChartPolynomialTransitionUnit R ι i j) := by
  rw [standardChartHomogeneousIdealOverlapEquiv_mk,
    standardChartPolynomialTransition_other, map_mul]

end ProjectiveSpace
